apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "swagger-editor-backend.fullname" . }}-config
  labels:
    {{- include "swagger-editor-backend.labels" . | nindent 4 }}
data:
  GITLAB_PROJECT: {{ .Values.gitlab.project | quote }}
  GITLAB_BRANCH: {{ .Values.gitlab.branch | quote }}
  GITLAB_URL: {{ .Values.gitlab.url | quote }}
  SERVER_PORT: {{ .Values.serverPort | quote }}
  SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE: {{ .Values.multipartMaxFileSize | quote }}
  SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE: {{ .Values.multipartMaxRequestSize | quote }}
