apiVersion: v1
kind: Secret
metadata:
  name: {{ include "swagger-editor-backend.fullname" . }}-github
  labels:
    {{- include "swagger-editor-backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  GITHUB_TOKEN: {{ required "A valid githubToken is required! Provide it via --set githubToken=... or values-local.yaml" .Values.githubToken | quote }}
