apiVersion: v1
kind: Secret
metadata:
  name: {{ include "swagger-editor-backend.fullname" . }}-gitlab
  labels:
    {{- include "swagger-editor-backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  GITLAB_TOKEN: {{ required "A valid gitlabToken is required! Provide it via --set gitlabToken=... or values-local.yaml" .Values.gitlabToken | quote }}
